name: Deploy CV to S3

on:
  push:
    branches: [main]
    paths:
      - 'public/resume.pdf'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload CV to S3
        run: |
          aws s3 cp ./public/resume.pdf s3://${{ secrets.S3_BUCKET }}/resume.pdf
